### ISSUE TITLE
Consider ActivityPub

### ISSUE THREAD

**Issue by jeroenpraat** [OkunaOrg/okuna-app#115]
In the FAQ I read: 

"Will Openbook be decentralised?

We want to get there eventually. We’re looking into Solid MIT approach (The one from Tim Berners Lee) and we’re very pleased with it so far."

Please consider implementing [ActivityPub](https://www.w3.org/TR/activitypub/)! It's a W3C standard and is already live on multiple projects (incl. Mastodon). It can even work when Openbook is still centralized. It's actually the only relevant social protocol today.

See also [Wikipedia](https://en.wikipedia.org/wiki/ActivityPub). Don't make Openbook the next walled garden!

**Comment by jeroenpraat** [comment]
sorry, wrong section

**Comment by fifn2** [comment]
@jeroenpraat What did you mean by "wrong section"? I think this is valid

**Comment by jeroenpraat** [comment]
@fifn2 See https://github.com/OkunaOrg/okuna-www/issues/84

**Comment by jeroenpraat** [comment]
@fifn2 Oh nevermind, it should indeed be opened. Closed it by accident probably.

**Comment by jeroenpraat** [comment]
Now I see it. The valid issue is https://github.com/OkunaOrg/okuna-api/issues/184
