### ISSUE TITLE
Confusing default sort order when reading comments

### ISSUE THREAD

**Issue by uiboy** [OkunaOrg/okuna-app#195]
When coming from a notification about a comment, we enforce the default sort order to new -> old. 
1. This is confusing for users who usually read comments old->new and therefore have this stored as their preference. 
2. When they now write a new comment we also sort from new -> old to place the comment on top. 

We should preserve the chosen order even when coming from a notification. Also if order is old->new, when writing a new comment... we should get latest comments but it should be added to the bottom of the stack and shown to the user in the right order. 

When sorted new->old we should get latest comments and add it on top of the stack in the right order.

**Comment by phoerious** [comment]
This is driving me nuts. I still haven't quite figured out in which order comments are actually shown. It seems to keep flipping almost at random. However, after commenting, the order only seems to be reversed after the first comment. Once I correct it, it stays on that order, although only for that post.

Thanks for taking care of this.
