### ISSUE TITLE
Email validation on sign up not as people are used to

### ISSUE THREAD

**Issue by ManuelFeller** [OkunaOrg/okuna-app#343]
When you accidentally enter a space in the email address field when signing up the app tells you that you have entered an invalid email address.

**To Reproduce**
1. Enter the sign up procedure
2. Type an email address followed by a space
3. Try to finish the sign up
4. See error message "enter valid email address"

**Expected behavior**
Most people expect that leading or trailing spaces surrounding an email address are trimmed automatically (since they are not really allowed in there). So this should be done before validating the string.
Another option would be to somehow highlight the string (select it completely?) so that the user can see the space(s) easily...

Discovered on Android, latest version of the app

**Comment by uiboy** [comment]
@ManuelFeller this was fixed in the last release - 0.0.51. Will close this issue.
