### ISSUE TITLE
Home stream has state:bad element error at times

### ISSUE THREAD

**Issue by uiboy** [OkunaOrg/okuna-app#450]
Some users have reported seeing an error on the home timeline while its loading. Something is going wrong in its initialization perhaps sometimes. 

There is no particular way to reproduce this, though Ive a feeling this has something to do with the `OBPostsStream` widgets `initialPosts` state. Sentry is more helpful 

https://sentry.openbook.social/okuna/okuna-app/issues/12594/?query=is:unresolved%20no%20element 

<img width="417" alt="Screenshot 2019-10-25 at 18 11 57" src="https://user-images.githubusercontent.com/5570900/67587089-6330ce80-f753-11e9-9c0e-6352b458177c.png">

**Comment by lifenautjoe** [comment]
Oh thought this had been fixed 🤔
