### ISSUE TITLE
Possible memleak when scrolling fast through timeline

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-app#488]
When scrolling fast through a timeline with multiple videos, there are setState detached errors in regards to amongst other, the fetching of the post media call. Thiis might indicate a memory leak.

Profile.

CC @Komposten

**Comment by uiboy** [comment]
Fixed in commit https://github.com/OkunaOrg/okuna-app/pull/493/commits/4fd1151676b24bb9a1ff68c29b9f404bbe460a6c
