### ISSUE TITLE
Problem starting project (clean install)

### ISSUE THREAD

**Issue by iboldurev** [OkunaOrg/okuna-app#504]
<img width="1282" alt="Screenshot 2020-01-26 at 10 03 49" src="https://user-images.githubusercontent.com/17103170/73132409-5d34dd00-4023-11ea-977a-f1095fbfd5c6.png">

`flutter run --flavor development
Launching lib/main.dart on iPhone 11 in debug mode...

Running Xcode build...

Xcode build done.                                            5.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/connectivity'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/device_info'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/file_picker'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/flutter_ffmpeg'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/flutter_image_compress'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/flutter_secure_storage'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/image_cropper'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/image_picker'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/intercom_flutter'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/libwebp'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/onesignal_flutter'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/package_info'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/path_provider'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/screen'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/share'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/shared_preferences'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/sqflite'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/uni_links'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/url_launcher'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/video_player'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/video_thumbnail'
    ld: warning: directory not found for option
    '-F/Users/iboldurev/Documents/Develop/Projects/okuna-app/build/ios/Debug-development-iphonesimulator/wakelock'
    ld: framework not found TOCropViewController
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 11.`

**Comment by lifenautjoe** [comment]
This seems to suggest the iOS dependencies have not been installed. Can you go to the ios directory and run pod install?

**Comment by iboldurev** [comment]
@lifenautjoe, Thanks

pod install starts automatically when the project starts, but I tried to manually start it and it worked, there was one compilation error but I fixed it and everything went smoothly
