### ISSUE TITLE
Unable to compile with Version 11.4.1

### ISSUE THREAD

**Issue by apicemai** [OkunaOrg/okuna-app#526]
**Describe the bug**
After you run flutter run --flavor development the code does not complete with the following errors:

```
Compiler message:
lib/main.dart:304:7: Error: No named parameter with the name 'onError'.
      onError: (error, stackTrace) async {
      ^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/overrides.dart:65:12:
Context: Found this candidate, but the arguments don't match.
  static R runWithHttpOverrides<R>(R body(), HttpOverrides overrides) {
           ^^^^^^^^^^^^^^^^^^^^
lib/widgets/video_player/widgets/chewie/chewie_player.dart:133:31: Error: No
named parameter with the name 'isInitialRoute'.
      settings: RouteSettings(isInitialRoute: false),
                              ^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/widgets/navigator.dart:458:9: Context: Found
this candidate, but the arguments don't match.
  const RouteSettings({
        ^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.4/lib/src/picture
_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed
constructor that takes no arguments.
  PictureStream();                                                      
  ^^^^^^^^^^^^^                                                         
Running Xcode build...                                                  
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.4/lib/src/picture
_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed
constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {      
```

**To Reproduce**
1. Clone the repository into your Mac Using Xcode 11.4.1
2. Run flutter run --flavor development

**Expected behavior**
The application should compile and install on the connected device or simulator
**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4

**Smartphone (please complete the following information):**
 - Device: IphoneXs
 - OS:13.4.1

**Comment by Komposten** [comment]
Try changing flutter to use the master channel by running:
```
flutter channel master
flutter upgrade
```

**Comment by apicemai** [comment]
Hi Komposten,

Thanks for the quick update I've tried that as well but complains on the same issue. 

For reference here is the flutter version:
 Flutter 1.19.0-1.0.pre.29 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0177d4293c (2 hours ago) • 2020-05-11 09:41:38 -0700
Engine • revision d96f962ca2
Tools • Dart 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

One thing to note also is that the flutter_svg I can fix by updating the pubspec file with the latest version.

However no matter what I do I cannot get past the chewie errors

**Comment by apicemai** [comment]
> Try changing flutter to use the master channel by running:
> 
> ```
> flutter channel master
> flutter upgrade
> ```
> 
> (You might also need to be on the `develop` branch in okuna-app; I don't know which flutter version the `master` branch uses.)

We you a beer! develop branch did it, wondering if the master readme should be updated with  the master branch flutter version. :)
