### ISSUE TITLE
Filter in timelime gives getter data called on null error.

### ISSUE THREAD

**Issue by alsiPanda** [OkunaOrg/okuna-app#543]
When I click on the filter button or any other button related to modal service, I get an error saying `getter data called on null `. I have tracked the error all the way to the `provider.dart` where the `context.inheritFromWidgetOfExactSameType` is shown as deprecated. I tried changing it to `context.dependOnInheritedWidgetOfExactType<_OpenbookProvider>()`. But still getting the same error.
 Any idea where things could be going wrong ? UserService seems to be working since I can see the posts in timeline.

**Comment by narayanan-ka** [comment]
I gave up on this error last week. Have left it for now. working on other aspects. Can someone from Okuna help us out.

**Comment by alsiPanda** [comment]
@lifenautjoe Hi, can you drop a hint on why this kind of error would happen ? I can't seem to find anything on google or stack.

**Comment by Komposten** [comment]
Try the `develop` or `release/1.0.1` branch instead of `master` (master isn't fully up to date).

**Comment by alsiPanda** [comment]
> Try the `develop` or `release/1.0.1` branch instead of `master` (master isn't fully up to date).

@Komposten, thanks for the reply. Any idea which portions could be incomplete ? I have made quite some modifications in the file I downloaded, transferring them would be painful, so if there's any way I could avoid that ?

**Comment by Komposten** [comment]
Not really; I haven't really worked on Okuna for a while. Joel is the one that maintains the app and keeps it up to date with Flutter. Though, you should just be able to diff master and develop and look for changes that might be related to the null error. Or you could try to copy your changes to a new branch, rebase onto develop and resolve the conflicts that pop up (given that there aren't too many, of course).

**Comment by kitlu007** [comment]
@lifenautjoe Any suggestions?

**Comment by lifenautjoe** [comment]
Hi @kitlu007  and @alsiPanda . What flutter version are you using? We recently upgraded to the latest version on stable and it had some breaking changes related to inheritFromWidgetOfExactSameType and a couple other things.

**Comment by alsiPanda** [comment]
@lifenautjoe @Komposten thanks a lot, followed the suggestions. I was using the master version, switched to the latest release version and copied all my additions and changes. And the error dissappeared as a result. But then, few hours back, it suddenly reappeared again. I have cross-checked the provider.dart file and modalservice.dart file with the release version just to be sure. There doesn't seem to be any accidental changes on my end. 
I tried adding print statements in create_post.dart to track the error. It seems that the error is thrown when trying to get the provider in build in create_post after it gets called from modalservice.

**Comment by kitlu007** [comment]
Hi @lifenautjoe any suggestive solution to the above post by aslipanda. Perhaps I could take not of it as well.

**Comment by kitlu007** [comment]
@lifenautjoe any suggestions?

**Comment by alsiPanda** [comment]
Any particular file I need to check which could be causing the error ?
