### ISSUE TITLE
Founder badges don't show up sometimes?

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-app#97]
There has been a couple reports that state founder badges are not show. Investigate.

**Comment by thadguidry** [comment]
They show on Profile page, but not in Communities, perhaps elsewhere.

**Comment by uiboy** [comment]
Also realised by talking to some users, the problem is that other people are not seeing the badges. The person themselves see it. So its probably in the UserProfileView in some cases the badge is not shown.
